class LoginLocator:
    USERNAME="//input[@placeholder='your.email@company.com']"
    OTP1="(//input[@inputmode='numeric'])[1]"
    OTP2="(//input[@inputmode='numeric'])[2]"
    OTP3="(//input[@inputmode='numeric'])[3]"
    OTP4="(//input[@inputmode='numeric'])[4]"
    OTP5="(//input[@inputmode='numeric'])[5]"
    OTP6="(//input[@inputmode='numeric'])[6]"
    VERIFY="//button[text()='Verify & Sign In']"
    CONTINUE="//button[text()='Continue']"
    EMAILREQUIRED="//p[text()='Email is required']"
    BUISNESSNOTFOUND="//div[text()='Business not found']"
    INVALIDOTPERROR="//div[text()='Invalid OTP']"
    LOFINSUCCESSFULL="//div[text()='Login successful']"