class ProductLocator:
    PRODUCTS="//a[@href='/products']"
    ADDPRODUCT="//button[contains(@class,'text-primary-foreground')]"
    VERIFYADDPRODUCTTEXT="//p[text()='Fill in the details to add a new product to your inventory']"
    SELECTPRODUCTTYPEDROPDOWN="//select[@id='productType']"
    SELECTFINISHEDPRODUCT="//option[text()='Finished Product']"
    ENTERPRODUCTNAME="//input[@placeholder='Enter product name']"
    CATEGORYDROPDOWN="//select[@name='category']"
    MATERIALDROPDOWN="//select[@name='materialType']"
    COSTPRICE="//input[@name='costPrice']"
    SELLINGPRICE="//input[@name='sellingPrice']"
    STOCK="//input[@name='stock']"
    ADDPRODUCTFORMBUTTON="(//button[text()='Add Product'])[2]"
    PROFITPERUNITVALUE="(//span[contains(@class, 'font-semibold')])[2]"
    PROFITPERCENTAGE="(//span[contains(@class, 'text-green-600')])[2]"
    PRODUCTNAME="//span[@class='block truncate']"